dist: bionic
sudo: required

language: minimal

cache:
  directories: [$HOME/.cache/snapcraft/]

addons:
  apt:
    packages:
    - jq

arch:
  - amd64
  - arm64

env:
  - CHANNEL=edge
  - CHANNEL=candidate

script:
  - set -e
  - until sudo snap install snapcraft --classic; do echo "Retrying"; done
  - sudo apt remove --purge --assume-yes lxd lxd-client
  - sudo snap install lxd
  - sudo /snap/bin/lxd waitready
  - sudo /snap/bin/lxd init --auto
  - sudo adduser $USER lxd
  # Decrypt the login credentials.
  - openssl aes-256-cbc -K $encrypted_74010c3d9f56_key -iv $encrypted_74010c3d9f56_iv
    -in snapcraft-login.enc -out snapcraft-login -d
  - snapcraft login --with snapcraft-login
  - sudo ./scripts/snap $CHANNEL
  # XXX Flacky, two .snap files will make this go crazy.
  - |
    if [ ! -f *".snap" ]; then
      exit 0
    fi
  # Publish to the snap store channel.
  - |
    if [ "$TRAVIS_BRANCH" = "master" ] && [ "$TRAVIS_EVENT_TYPE" != "pull_request" ]; then
      snapcraft push *.snap --release $CHANNEL
    fi
