name: geth
version: master
summary: Official Go implementation of the Ethereum protocol
description: |
  Go Ethereum is one of the three original implementations
  (along with C++ and Python) of the Ethereum protocol. It
  is written in Go, fully open source and licensed under
  the GNU LGPL v3.

grade: stable
confinement: strict

apps:
  abigen:
    command: abigen
  bootnode:
    command: bootnode
  evm:
    command: evm
  faucet:
    command: faucet
  geth:
    command: geth
    plugs:
      - network
      - network-bind
      - removable-media
  puppeth:
    command: puppeth
  rlpdump:
    command: rlpdump
  wnode:
    command: wnode

parts:
  geth:
    build-snaps: [go]
    source: https://github.com/ethereum/go-ethereum.git
    source-tag: master
    plugin: make
    override-build: |
      make all
      cp $SNAPCRAFT_PART_BUILD/build/bin/* $SNAPCRAFT_PART_INSTALL
